name: Generate Privacy Policy HTML

on:
  push:
    branches:
      - main
    paths:
      - 'privacy-policy.md'
      - '.github/workflows/generate-privacy-html.yml'
  workflow_dispatch:

jobs:
  generate-html:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          npm install marked
      
      - name: Create generator script
        run: |
          cat > generate.js << 'EOFSCRIPT'
          const fs = require('fs');
          const marked = require('marked');
          
          // Read the markdown file
          const markdown = fs.readFileSync('privacy-policy.md', 'utf8');
          
          // Extract version and date from markdown
          const versionMatch = markdown.match(/\*\*Version:\*\*\s*([\d.]+)/);
          const dateMatch = markdown.match(/\*\*Last Updated:\*\*\s*([^\n]+)/);
          const effectiveDateMatch = markdown.match(/\*\*Effective Date:\*\*\s*([^\n]+)/);
          
          const version = versionMatch ? versionMatch[1] : '1.0';
          const lastUpdated = dateMatch ? dateMatch[1] : 'October 6, 2025';
          const effectiveDate = effectiveDateMatch ? effectiveDateMatch[1] : 'October 6, 2025';
          
          // Convert markdown to HTML
          const contentHtml = marked.parse(markdown);
          
          // Create full HTML with styling
          const html = `<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <meta name="description" content="AkademiTrack Privacy Policy - Learn how we protect your data and comply with GDPR">
              <meta name="keywords" content="privacy policy, GDPR, data protection, AkademiTrack">
              <title>Privacy Policy - AkademiTrack v${version}</title>
              <style>
                  * {
                      margin: 0;
                      padding: 0;
                      box-sizing: border-box;
                  }

                  body {
                      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                      line-height: 1.6;
                      color: #1a1a1a;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      padding: 20px;
                  }

                  .container {
                      max-width: 900px;
                      margin: 0 auto;
                      background: white;
                      border-radius: 12px;
                      box-shadow: 0 10px 40px rgba(0, 0, 0, 0.2);
                      overflow: hidden;
                  }

                  .header {
                      background: linear-gradient(135deg, #4a5fd9 0%, #5b3f9e 100%);
                      color: white;
                      padding: 40px;
                      text-align: center;
                  }

                  .header h1 {
                      font-size: 2.5em;
                      margin-bottom: 10px;
                  }

                  .version-badge {
                      display: inline-block;
                      background: rgba(255, 255, 255, 0.2);
                      padding: 5px 15px;
                      border-radius: 20px;
                      font-size: 0.9em;
                      margin-top: 10px;
                  }

                  .content {
                      padding: 40px;
                  }

                  h1, h2 {
                      color: #4a5fd9;
                      margin-top: 30px;
                      margin-bottom: 15px;
                      border-bottom: 2px solid #e8ecff;
                      padding-bottom: 10px;
                  }

                  h1 {
                      font-size: 2em;
                  }

                  h2 {
                      font-size: 1.8em;
                  }

                  h3 {
                      color: #5b3f9e;
                      margin-top: 20px;
                      margin-bottom: 10px;
                      font-size: 1.3em;
                  }

                  h4 {
                      color: #6b46c1;
                      margin-top: 15px;
                      margin-bottom: 8px;
                      font-size: 1.1em;
                  }

                  p, ul, ol {
                      margin-bottom: 15px;
                  }

                  ul, ol {
                      margin-left: 25px;
                  }

                  li {
                      margin-bottom: 8px;
                  }

                  blockquote {
                      background: #fff5f5;
                      border-left: 4px solid #e53e3e;
                      padding: 15px 20px;
                      margin: 20px 0;
                      border-radius: 4px;
                  }

                  blockquote strong {
                      color: #c53030;
                  }

                  table {
                      width: 100%;
                      border-collapse: collapse;
                      margin: 20px 0;
                      background: white;
                  }

                  th, td {
                      padding: 12px;
                      text-align: left;
                      border: 1px solid #e8ecff;
                  }

                  th {
                      background: #f0f4ff;
                      color: #4a5fd9;
                      font-weight: 600;
                  }

                  tr:hover {
                      background: #f9fafb;
                  }

                  a {
                      color: #4a5fd9;
                      text-decoration: none;
                      font-weight: 500;
                  }

                  a:hover {
                      text-decoration: underline;
                  }

                  code {
                      background: #f0f4ff;
                      padding: 2px 6px;
                      border-radius: 3px;
                      font-family: 'Courier New', monospace;
                      color: #5b3f9e;
                  }

                  .footer {
                      background: #2d3748;
                      color: white;
                      text-align: center;
                      padding: 20px;
                      font-size: 0.9em;
                  }

                  .toc {
                      background: #f0f4ff;
                      padding: 20px;
                      border-radius: 8px;
                      margin: 20px 0;
                  }

                  .toc h2 {
                      margin-top: 0;
                      font-size: 1.3em;
                      border: none;
                  }

                  .toc ul {
                      margin-left: 0;
                      list-style: none;
                  }

                  .toc li {
                      padding: 5px 0;
                  }

                  .back-to-top {
                      position: fixed;
                      bottom: 30px;
                      right: 30px;
                      background: #4a5fd9;
                      color: white;
                      width: 50px;
                      height: 50px;
                      border-radius: 50%;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      text-decoration: none;
                      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.2);
                      opacity: 0;
                      transition: opacity 0.3s;
                  }

                  .back-to-top.visible {
                      opacity: 1;
                  }

                  .back-to-top:hover {
                      background: #3a4fc9;
                  }

                  @media (max-width: 768px) {
                      .header h1 {
                          font-size: 1.8em;
                      }

                      .content {
                          padding: 20px;
                      }

                      table {
                          font-size: 0.9em;
                      }

                      th, td {
                          padding: 8px;
                      }

                      .back-to-top {
                          bottom: 20px;
                          right: 20px;
                          width: 45px;
                          height: 45px;
                      }
                  }
              </style>
          </head>
          <body>
              <a href="#top" class="back-to-top" id="backToTop">↑</a>
              
              <div class="container" id="top">
                  <div class="header">
                      <h1>🔒 Privacy Policy</h1>
                      <p>AkademiTrack - Automated Study Time Registration</p>
                      <div class="version-badge">Version ${version} | Last Updated: ${lastUpdated}</div>
                  </div>

                  <div class="content">
                      ${contentHtml}
                  </div>

                  <div class="footer">
                      <p>&copy; 2025 AkademiTrack - Developed by Mathias Hansen & Andreas Nilsen</p>
                      <p>This application is not officially affiliated with Akademiet or iSkole.net</p>
                      <p style="margin-top: 10px; font-size: 0.85em;">
                          Generated from <a href="https://github.com/CyberGutta/AkademiTrack/blob/main/privacy-policy.md" style="color: #90cdf4;">privacy-policy.md</a>
                      </p>
                  </div>
              </div>

              <script>
                  // Back to top button functionality
                  const backToTop = document.getElementById('backToTop');
                  
                  window.addEventListener('scroll', () => {
                      if (window.pageYOffset > 300) {
                          backToTop.classList.add('visible');
                      } else {
                          backToTop.classList.remove('visible');
                      }
                  });

                  backToTop.addEventListener('click', (e) => {
                      e.preventDefault();
                      window.scrollTo({
                          top: 0,
                          behavior: 'smooth'
                      });
                  });

                  // Smooth scroll for anchor links
                  document.querySelectorAll('a[href^="#"]').forEach(anchor => {
                      anchor.addEventListener('click', function (e) {
                          e.preventDefault();
                          const target = document.querySelector(this.getAttribute('href'));
                          if (target) {
                              target.scrollIntoView({
                                  behavior: 'smooth',
                                  block: 'start'
                              });
                          }
                      });
                  });
              </script>
          </body>
          </html>`;
          
          // Write the HTML file
          fs.writeFileSync('privacy-policy.html', html, 'utf8');
          console.log('✅ Generated privacy-policy.html');
          console.log('Version:', version);
          console.log('Last Updated:', lastUpdated);
          
          // Generate JSON API file
          const jsonApi = {
            version: version,
            lastUpdated: lastUpdated,
            effectiveDate: effectiveDate,
            url: 'https://cybergutta.github.io/AkademietTrack/privacy-policy.html',
            markdownUrl: 'https://raw.githubusercontent.com/CyberGutta/AkademietTrack/main/privacy-policy.md'
          };
          
          fs.writeFileSync('privacy-policy.json', JSON.stringify(jsonApi, null, 2), 'utf8');
          console.log('✅ Generated privacy-policy.json');
          EOFSCRIPT
      
      - name: Generate HTML from Markdown
        run: node generate.js
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add privacy-policy.html
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "🤖 Auto-generate privacy-policy.html from markdown [skip ci]"
            git push
            echo "✅ Privacy policy HTML updated"
          fi
